apiVersion: v1
kind: Service
metadata:
  name: discord-bot-service
spec:
  selector:
    app: discord-bot
  ports:
  - name: bot-bot
    protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30750
  - name: logstash-port  
    protocol: TCP
    port: 32405
    targetPort: 32405
    nodePort: 32406
  - name: openai-http
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32407
  - name: openai-https
    protocol: UDP
    port: 443
    targetPort: 443
    nodePort: 32408
  type: NodePort
